DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS hand;
DROP TABLE IF EXISTS round;
DROP TABLE IF EXISTS game;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  emoji TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE card (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT NOT NULL,
  suit TEXT NOT NULL,
  suit_unicode TEXT NOT NULL,
  display_text TEXT NOT NULL
);

CREATE TABLE game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE round (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hand (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  round_id INTEGER NOT NULL,
  high_card_id INTEGER NOT NULL,
  low_card_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES user (id),
  FOREIGN KEY (round_id) REFERENCES round (id),
  FOREIGN KEY (high_card_id) REFERENCES card (id),
  FOREIGN KEY (low_card_id) REFERENCES card (id)
);
